---
apiVersion: v1
kind: Service
metadata:
 name: companies-service
 labels:
   app: companies-service
spec:
 type: NodePort
 ports:
 - port: 8081
   nodePort: 32728
   protocol: TCP
 selector:
   app: companies-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: companies-service-deploy
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: companies-service
    spec: 
      containers:
      - name: companies-service-pod
        image: pozhidaev/companies-service:1.0.0-1-rc
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: config
              key: environment
        - name: MONGO_ENABLED
          value: "true"