# Build stage
FROM microsoft/dotnet:2.1-sdk AS build

# set working directory
WORKDIR /app

# Restore
COPY src/Service/Service.csproj ./src/Service/ 
COPY nuget/Companies.Client.1.0.0.nupkg ./nuget/ 
COPY nuget/Companies.Interface.1.0.0.nupkg ./nuget/ 
COPY src/Service/Service.csproj ./src/Service/
RUN dotnet restore src/Service/Service.csproj  -s ./nuget -s https://api.nuget.org/v3/index.json
COPY src/Process/Process.csproj ./src/Process/
RUN dotnet restore src/Process/Process.csproj
COPY test/Service.Test/Service.Test.csproj ./test/Service.Test/
RUN dotnet restore test/Service.Test/Service.Test.csproj

# Copy src
COPY . .

# Test
##RUN dotnet test test/Service.Test/Service.Test.csproj \
##    && dotnet test test/Client.Test/Client.Test.csproj
