---
# Console logger
- descriptor: "pip-services3-commons:logger:console:default:1.0"
  level: "trace"

# Performance counters that posts values to log
- descriptor: "pip-services3-commons:counters:log:default:1.0"
  level: "trace"


{{#if MONGO_ENABLED}}
# MongoDB Persistence
- descriptor: "companies-audit:persistence:mongodb:default:1.0"
  collection: {{MONGO_COLLECTION}}{{^MONGO_COLLECTION}}problem-companies{{/MONGO_COLLECTION}}
  connection:
    uri: {{MONGO_SERVICE_URI}}
    host: {{MONGO_SERVICE_HOST}}{{^MONGO_SERVICE_HOST}}localhost{{/MONGO_SERVICE_HOST}}
    port: {{MONGO_SERVICE_PORT}}{{^MONGO_SERVICE_PORT}}27017{{/MONGO_SERVICE_PORT}}
    database: {{MONGO_DB}}{{^MONGO_DB}}app{{/MONGO_DB}}
  credential:
    username: {{MONGO_USER}}
    password: {{MONGO_PASS}}
{{/if}}

{{^MOCK_ENABLED}}{{^MONGO_ENABLED}}
# Default in-memory persistence
- descriptor: "companies-audit:persistence:memory:default:1.0"
{{/MONGO_ENABLED}}{{/MOCK_ENABLED}}

# Companies HTTP client
- descriptor: "companies-service:client:http:default:*"
  connection:
    protocol: {{COMPANIES_SERVICE_PROTOCOL}}{{^COMPANIES_SERVICE_PROTOCOL}}http{{/COMPANIES_SERVICE_PROTOCOL}}
    host: {{COMPANIES_SERVICE_HOST}}{{^COMPANIES_SERVICE_HOST}}localhost{{/COMPANIES_SERVICE_HOST}}
    port: {{COMPANIES_SERVICE_PORT}}{{^COMPANIES_SERVICE_PORT}}8088{{/COMPANIES_SERVICE_PORT}}


# Default controller
- descriptor: "companies-audit:controller:default:default:1.0"
  mailsettings:
    host: "0.0.0.0"
    from_address: "robot@service.com"
    to_address: "admin@service.com"  
    subj: "BAD company found"
    body: "[BANKCODE][ACCCODE][STATECODE][IBAN][NAME][CONTRACTDATE][NOTE][EMPLOYEE_ID]"
  intervals:
    interval: 10000000
    delay: 10000000

# Common HTTP endpoint
- descriptor: "pip-services3:endpoint:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: {{{HTTP_PORT}}}{{^HTTP_PORT}}8080{{/HTTP_PORT}}

# HTTP service version 1.0
#- descriptor: "companies-audit:service:http:default:1.01"

# Heartbeat service
- descriptor: "pip-services3:heartbeat-service:http:default:1.0"
  route: heartbeat

# Status service
- descriptor: "pip-services3:status-service:http:default:1.0"
  route: status

